### ISSUE TITLE
[META] Ideas 💡

### ISSUE THREAD

**Issue by moul** [moul/asanaman#5]
* [ ] extract `moul.io/asanaman/Asana` -> `moul.io/asana`
* [ ] manage more API endpoints
* [ ] generate cool examples from "make generate", add them in README.md
